
import java.awt.Dimension;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import static jdk.nashorn.internal.objects.NativeMath.round;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ljn
 */
public class MainMenu extends javax.swing.JFrame
{

    OpenHashTable theTable = new OpenHashTable(2);

    /**
     * Creates new form NewJFrame
     */
    public MainMenu()
    {
        initComponents();
        setSize(600, 470);
        mainPan.setVisible(true);
        addPan.setVisible(false);
        removePan.setVisible(false);
        searchPan.setVisible(false);
        displayPan.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderSelectionRadButGroup = new javax.swing.ButtonGroup();
        empTypeSelectionRadButGroup = new javax.swing.ButtonGroup();
        mainPan = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        addBut = new javax.swing.JButton();
        removeBut = new javax.swing.JButton();
        searchBut = new javax.swing.JButton();
        displayBut = new javax.swing.JButton();
        modifyBut = new javax.swing.JButton();
        loadBut = new javax.swing.JButton();
        exitBut = new javax.swing.JButton();
        addPan = new javax.swing.JPanel();
        homeButFromAddPan = new javax.swing.JButton();
        addTitle = new javax.swing.JLabel();
        empNumLabel = new javax.swing.JLabel();
        empNumInput = new javax.swing.JFormattedTextField();
        fNameLabel = new javax.swing.JLabel();
        fNameInput = new javax.swing.JTextField();
        lNameLabel = new javax.swing.JLabel();
        lNameInput = new javax.swing.JTextField();
        sexLabel = new javax.swing.JLabel();
        maleRadBut = new javax.swing.JRadioButton();
        femaleRadBut = new javax.swing.JRadioButton();
        otherRadBut = new javax.swing.JRadioButton();
        workLocationLabel = new javax.swing.JLabel();
        workLocationDropdown = new javax.swing.JComboBox<>();
        fullTimeRadBut = new javax.swing.JRadioButton();
        partTimeRadBut = new javax.swing.JRadioButton();
        deductionsRateLabel = new javax.swing.JLabel();
        deductionsRateInput = new javax.swing.JFormattedTextField();
        saveButFromAddPan = new javax.swing.JButton();
        cancelButFromAddPan = new javax.swing.JButton();
        employeeTypeLabel = new javax.swing.JLabel();
        fullTimeInputsPan = new javax.swing.JPanel();
        hourlyWageLabel = new javax.swing.JLabel();
        hoursPerWeekLabel = new javax.swing.JLabel();
        weeksPerYearLabel = new javax.swing.JLabel();
        hourlyWageInput = new javax.swing.JFormattedTextField();
        hoursPerWeekInput = new javax.swing.JFormattedTextField();
        weeksPerYearInput = new javax.swing.JFormattedTextField();
        partTimeInputsPan = new javax.swing.JPanel();
        annualSalaryLabel = new javax.swing.JLabel();
        annualSalaryInput = new javax.swing.JFormattedTextField();
        exitBut1 = new javax.swing.JButton();
        errorEmpNum = new javax.swing.JLabel();
        empExistNotice = new javax.swing.JLabel();
        percentSymbolLabel = new javax.swing.JLabel();
        saveSuccessNotice = new javax.swing.JLabel();
        removePan = new javax.swing.JPanel();
        removeTitle = new javax.swing.JLabel();
        homeButFromRemovePan = new javax.swing.JButton();
        employeeNumberLabel = new javax.swing.JLabel();
        empNumRemoveSearchInput = new javax.swing.JTextField();
        removeNoteLabel = new javax.swing.JLabel();
        note2Label = new javax.swing.JLabel();
        searchButToRemove = new javax.swing.JButton();
        exitBut2 = new javax.swing.JButton();
        notFoundLabel = new javax.swing.JLabel();
        removeResultPan = new javax.swing.JPanel();
        removeNoBut = new javax.swing.JButton();
        removeYesBut = new javax.swing.JButton();
        removeConfirmLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        outPutTable1 = new javax.swing.JTable();
        removeSuccessNotice = new javax.swing.JLabel();
        searchPan = new javax.swing.JPanel();
        searchTitle1 = new javax.swing.JLabel();
        homeButFromRemovePan1 = new javax.swing.JButton();
        employeeNumberLabel1 = new javax.swing.JLabel();
        empNumSearchInput = new javax.swing.JTextField();
        searchNoteLabel1 = new javax.swing.JLabel();
        note2Label1 = new javax.swing.JLabel();
        searchButToRemove1 = new javax.swing.JButton();
        exitBut3 = new javax.swing.JButton();
        searchResultPan = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        empInfoDisplayLabel1 = new javax.swing.JLabel();
        notFoundLabelSearchPan = new javax.swing.JLabel();
        displayPan = new javax.swing.JPanel();
        diaplayTitle = new javax.swing.JLabel();
        homeButFromRemovePan2 = new javax.swing.JButton();
        exitBut4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        outPutTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setMinimumSize(new java.awt.Dimension(600, 450));
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPan.setMaximumSize(new java.awt.Dimension(600, 450));
        mainPan.setMinimumSize(new java.awt.Dimension(600, 450));
        mainPan.setPreferredSize(new java.awt.Dimension(600, 450));
        mainPan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        Title.setText("Employee Database System");
        mainPan.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 360, 40));

        addBut.setText("Add");
        addBut.setMaximumSize(new java.awt.Dimension(50, 20));
        addBut.setMinimumSize(new java.awt.Dimension(50, 20));
        addBut.setPreferredSize(new java.awt.Dimension(50, 20));
        addBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickedAddFromMainPan(evt);
            }
        });
        mainPan.add(addBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 120, 60));

        removeBut.setText("Remove");
        removeBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickedRemoveFromMainPan(evt);
            }
        });
        mainPan.add(removeBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 120, 60));

        searchBut.setText("Search");
        searchBut.setMaximumSize(new java.awt.Dimension(50, 20));
        searchBut.setMinimumSize(new java.awt.Dimension(50, 20));
        searchBut.setPreferredSize(new java.awt.Dimension(50, 20));
        searchBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickedSearchButFromMainPan(evt);
            }
        });
        mainPan.add(searchBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 120, 60));

        displayBut.setText("Display");
        displayBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickedDisplayButFromMainPan(evt);
            }
        });
        mainPan.add(displayBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 120, 60));

        modifyBut.setText("Modify");
        mainPan.add(modifyBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 120, 60));

        loadBut.setText("Load");
        mainPan.add(loadBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 120, 60));

        exitBut.setText("Exit");
        exitBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickedExitButFromMainPan(evt);
            }
        });
        mainPan.add(exitBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, -1, -1));

        getContentPane().add(mainPan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        addPan.setMaximumSize(new java.awt.Dimension(600, 450));
        addPan.setMinimumSize(new java.awt.Dimension(600, 450));
        addPan.setPreferredSize(new java.awt.Dimension(600, 450));
        addPan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homeButFromAddPan.setText("Home");
        homeButFromAddPan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickedHomeButFromAddPan(evt);
            }
        });
        addPan.add(homeButFromAddPan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        addTitle.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        addTitle.setText("Add");
        addPan.add(addTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        empNumLabel.setText("Employee Number:");
        addPan.add(empNumLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, 20));

        empNumInput.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#+0"))));
        addPan.add(empNumInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 140, 30));

        fNameLabel.setText("First Name:");
        addPan.add(fNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 90, 20));

        fNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNameInputActionPerformed(evt);
            }
        });
        addPan.add(fNameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 140, -1));

        lNameLabel.setText("Last Name:");
        addPan.add(lNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 90, 20));
        addPan.add(lNameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 140, -1));

        sexLabel.setText("Sex:");
        addPan.add(sexLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 40, 20));

        genderSelectionRadButGroup.add(maleRadBut);
        maleRadBut.setText("Male");
        addPan.add(maleRadBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        genderSelectionRadButGroup.add(femaleRadBut);
        femaleRadBut.setText("Female");
        addPan.add(femaleRadBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, -1));

        genderSelectionRadButGroup.add(otherRadBut);
        otherRadBut.setText("Other");
        addPan.add(otherRadBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, -1, -1));

        workLocationLabel.setText("Work Location:");
        addPan.add(workLocationLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 120, 20));

        workLocationDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Mississauga", "Ottawa", "Chicago" }));
        workLocationDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workLocationDropdownActionPerformed(evt);
            }
        });
        addPan.add(workLocationDropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));

        empTypeSelectionRadButGroup.add(fullTimeRadBut);
        fullTimeRadBut.setText("Full Time");
        fullTimeRadBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullTimeRadButClicked(evt);
            }
        });
        addPan.add(fullTimeRadBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        empTypeSelectionRadButGroup.add(partTimeRadBut);
        partTimeRadBut.setText("Part Time");
        partTimeRadBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partTimeRadButClicked(evt);
            }
        });
        addPan.add(partTimeRadBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        deductionsRateLabel.setText("Deductions Rate:");
        addPan.add(deductionsRateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 160, 20));

        deductionsRateInput.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0.00"))));
        addPan.add(deductionsRateInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 70, -1));

        saveButFromAddPan.setText("Save");
        saveButFromAddPan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickedSaveButFromAddPan(evt);
            }
        });
        addPan.add(saveButFromAddPan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 70, -1));

        cancelButFromAddPan.setText("Cancel");
        cancelButFromAddPan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickedCanelButFromAddPan(evt);
            }
        });
        addPan.add(cancelButFromAddPan, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, -1, -1));

        employeeTypeLabel.setText("Employee Type:");
        addPan.add(employeeTypeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 130, 20));

        fullTimeInputsPan.setMaximumSize(new java.awt.Dimension(200, 200));

        hourlyWageLabel.setText("Hourly Wage:");

        hoursPerWeekLabel.setText("Hours Per Week:");

        weeksPerYearLabel.setText("Weeks Per Year:");

        hourlyWageInput.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        hoursPerWeekInput.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        weeksPerYearInput.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        javax.swing.GroupLayout fullTimeInputsPanLayout = new javax.swing.GroupLayout(fullTimeInputsPan);
        fullTimeInputsPan.setLayout(fullTimeInputsPanLayout);
        fullTimeInputsPanLayout.setHorizontalGroup(
            fullTimeInputsPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fullTimeInputsPanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fullTimeInputsPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fullTimeInputsPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(hourlyWageInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fullTimeInputsPanLayout.createSequentialGroup()
                            .addComponent(weeksPerYearLabel)
                            .addGap(24, 24, 24)
                            .addGroup(fullTimeInputsPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(weeksPerYearInput, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(hoursPerWeekInput, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(fullTimeInputsPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(hourlyWageLabel)
                        .addComponent(hoursPerWeekLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fullTimeInputsPanLayout.setVerticalGroup(
            fullTimeInputsPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fullTimeInputsPanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fullTimeInputsPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hourlyWageLabel)
                    .addComponent(hourlyWageInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(fullTimeInputsPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hoursPerWeekInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hoursPerWeekLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fullTimeInputsPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weeksPerYearLabel)
                    .addComponent(weeksPerYearInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        addPan.add(fullTimeInputsPan, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 230, 120));

        annualSalaryLabel.setText("Annual Salary:");

        annualSalaryInput.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        javax.swing.GroupLayout partTimeInputsPanLayout = new javax.swing.GroupLayout(partTimeInputsPan);
        partTimeInputsPan.setLayout(partTimeInputsPanLayout);
        partTimeInputsPanLayout.setHorizontalGroup(
            partTimeInputsPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(partTimeInputsPanLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(annualSalaryLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(annualSalaryInput, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );
        partTimeInputsPanLayout.setVerticalGroup(
            partTimeInputsPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(partTimeInputsPanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(partTimeInputsPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(annualSalaryInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(annualSalaryLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        addPan.add(partTimeInputsPan, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 240, 50));

        exitBut1.setText("Exit");
        exitBut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBut1ActionPerformed(evt);
            }
        });
        addPan.add(exitBut1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, -1, -1));

        errorEmpNum.setForeground(new java.awt.Color(255, 0, 51));
        errorEmpNum.setText("The field you entered is not valid");
        addPan.add(errorEmpNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 180, 20));

        empExistNotice.setForeground(new java.awt.Color(255, 0, 51));
        empExistNotice.setText("No need to add, the employee already exist in the database!");
        addPan.add(empExistNotice, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 330, 30));

        percentSymbolLabel.setText("%");
        addPan.add(percentSymbolLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, -1));

        saveSuccessNotice.setForeground(new java.awt.Color(255, 0, 51));
        saveSuccessNotice.setText("The employee info are saved successfully!");
        addPan.add(saveSuccessNotice, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, -1, -1));

        getContentPane().add(addPan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 450));

        removePan.setMaximumSize(new java.awt.Dimension(1280, 960));
        removePan.setMinimumSize(new java.awt.Dimension(600, 450));
        removePan.setPreferredSize(new java.awt.Dimension(1280, 960));
        removePan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        removeTitle.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        removeTitle.setText("Remove");
        removePan.add(removeTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 32, -1, -1));

        homeButFromRemovePan.setText("Home");
        homeButFromRemovePan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButFromRemovePanclicked(evt);
            }
        });
        removePan.add(homeButFromRemovePan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        employeeNumberLabel.setText("Employee Number:");
        removePan.add(employeeNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 84, -1, -1));
        removePan.add(empNumRemoveSearchInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 80, -1));

        removeNoteLabel.setText("* You must enter the exact employee number.");
        removePan.add(removeNoteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 112, -1, -1));

        note2Label.setText(" Otherwise it will not find the employee.");
        removePan.add(note2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 132, -1, -1));

        searchButToRemove.setText("Search");
        searchButToRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButToRemoveActionPerformed(evt);
            }
        });
        removePan.add(searchButToRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

        exitBut2.setText("Exit");
        exitBut2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBut2ActionPerformed(evt);
            }
        });
        removePan.add(exitBut2, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 40, -1, -1));

        notFoundLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        notFoundLabel.setText("* The employee is not in the database.");
        removePan.add(notFoundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 309, 20));

        removeResultPan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        removeNoBut.setText("No");
        removeNoBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickedNoButFromRemovePan(evt);
            }
        });
        removeResultPan.add(removeNoBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        removeYesBut.setText("Yes");
        removeYesBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickedYesButFromRemovePan(evt);
            }
        });
        removeResultPan.add(removeYesBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        removeConfirmLabel.setText("Are you sure to remove the employee?");
        removeResultPan.add(removeConfirmLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 290, -1));

        outPutTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Emp Number", "First Name", "Last Name", "Sex", "Work Location", "Deductions Rate", "Full Time", "Part Time", "Annual Salary", "Hourly Wage", "Hours Per Week", "Weeks Per year", "Annual Income"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        outPutTable1.setMaximumSize(new java.awt.Dimension(1024, 768));
        outPutTable1.setPreferredSize(new java.awt.Dimension(1280, 960));
        jScrollPane2.setViewportView(outPutTable1);
        if (outPutTable1.getColumnModel().getColumnCount() > 0) {
            outPutTable1.getColumnModel().getColumn(0).setPreferredWidth(40);
            outPutTable1.getColumnModel().getColumn(1).setPreferredWidth(45);
            outPutTable1.getColumnModel().getColumn(2).setPreferredWidth(45);
            outPutTable1.getColumnModel().getColumn(3).setPreferredWidth(15);
            outPutTable1.getColumnModel().getColumn(4).setPreferredWidth(55);
            outPutTable1.getColumnModel().getColumn(5).setPreferredWidth(45);
            outPutTable1.getColumnModel().getColumn(6).setPreferredWidth(15);
            outPutTable1.getColumnModel().getColumn(7).setPreferredWidth(15);
            outPutTable1.getColumnModel().getColumn(8).setPreferredWidth(45);
            outPutTable1.getColumnModel().getColumn(9).setPreferredWidth(35);
            outPutTable1.getColumnModel().getColumn(10).setPreferredWidth(40);
            outPutTable1.getColumnModel().getColumn(11).setPreferredWidth(45);
            outPutTable1.getColumnModel().getColumn(12).setPreferredWidth(40);
        }

        removeResultPan.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1250, 100));

        removeSuccessNotice.setForeground(new java.awt.Color(255, 0, 0));
        removeSuccessNotice.setText("The employee has been removed successfully!");
        removeResultPan.add(removeSuccessNotice, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 360, 30));

        removePan.add(removeResultPan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 1270, 190));

        getContentPane().add(removePan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 960));

        searchPan.setMaximumSize(new java.awt.Dimension(600, 450));
        searchPan.setMinimumSize(new java.awt.Dimension(600, 450));
        searchPan.setPreferredSize(new java.awt.Dimension(600, 450));
        searchPan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchTitle1.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        searchTitle1.setText("Search");
        searchPan.add(searchTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 32, -1, -1));

        homeButFromRemovePan1.setText("Home");
        homeButFromRemovePan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickedHomeButFromSearchPan(evt);
            }
        });
        searchPan.add(homeButFromRemovePan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        employeeNumberLabel1.setText("Employee Number:");
        searchPan.add(employeeNumberLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 84, -1, -1));
        searchPan.add(empNumSearchInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 80, -1));

        searchNoteLabel1.setText("* You must enter the exact employee number.");
        searchPan.add(searchNoteLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 112, -1, -1));

        note2Label1.setText(" Otherwise it will not find the employee.");
        searchPan.add(note2Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 132, -1, -1));

        searchButToRemove1.setText("Search");
        searchButToRemove1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickedSearchButFromSearchPan(evt);
            }
        });
        searchPan.add(searchButToRemove1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

        exitBut3.setText("Exit");
        exitBut3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBut3ActionPerformed(evt);
            }
        });
        searchPan.add(exitBut3, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 40, -1, -1));

        searchResultPan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("jLabel4");
        searchResultPan.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel5.setText("jLabel5");
        searchResultPan.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        empInfoDisplayLabel1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                empInfoDisplayLabel1InputMethodTextChanged(evt);
            }
        });
        searchResultPan.add(empInfoDisplayLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 460, 30));

        searchPan.add(searchResultPan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 480, 180));

        notFoundLabelSearchPan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        notFoundLabelSearchPan.setText("* The employee is not in the database.");
        searchPan.add(notFoundLabelSearchPan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 309, 20));

        getContentPane().add(searchPan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        displayPan.setMaximumSize(new java.awt.Dimension(1024, 768));
        displayPan.setMinimumSize(new java.awt.Dimension(600, 450));
        displayPan.setPreferredSize(new java.awt.Dimension(1280, 960));
        displayPan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        diaplayTitle.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        diaplayTitle.setText("Display");
        displayPan.add(diaplayTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        homeButFromRemovePan2.setText("Home");
        homeButFromRemovePan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickedHomeButFromDisplayPan(evt);
            }
        });
        displayPan.add(homeButFromRemovePan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 27, -1, -1));

        exitBut4.setText("Exit");
        exitBut4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBut4ActionPerformed(evt);
            }
        });
        displayPan.add(exitBut4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1830, 27, -1, -1));

        outPutTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Emp Number", "First Name", "Last Name", "Sex", "Work Location", "Deductions Rate", "Full Time", "Part Time", "Annual Salary", "Hourly Wage", "Hours Per Week", "Weeks Per year", "Annual Income"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        outPutTable.setMaximumSize(new java.awt.Dimension(1024, 768));
        jScrollPane1.setViewportView(outPutTable);
        if (outPutTable.getColumnModel().getColumnCount() > 0) {
            outPutTable.getColumnModel().getColumn(0).setPreferredWidth(40);
            outPutTable.getColumnModel().getColumn(1).setPreferredWidth(45);
            outPutTable.getColumnModel().getColumn(2).setPreferredWidth(45);
            outPutTable.getColumnModel().getColumn(3).setPreferredWidth(15);
            outPutTable.getColumnModel().getColumn(4).setPreferredWidth(55);
            outPutTable.getColumnModel().getColumn(5).setPreferredWidth(45);
            outPutTable.getColumnModel().getColumn(6).setPreferredWidth(15);
            outPutTable.getColumnModel().getColumn(7).setPreferredWidth(15);
            outPutTable.getColumnModel().getColumn(8).setPreferredWidth(45);
            outPutTable.getColumnModel().getColumn(9).setPreferredWidth(35);
            outPutTable.getColumnModel().getColumn(10).setPreferredWidth(40);
            outPutTable.getColumnModel().getColumn(11).setPreferredWidth(45);
            outPutTable.getColumnModel().getColumn(12).setPreferredWidth(40);
        }

        displayPan.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 1250, 700));

        getContentPane().add(displayPan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 960));

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clickedAddFromMainPan(java.awt.event.ActionEvent evt)//GEN-FIRST:event_clickedAddFromMainPan
    {//GEN-HEADEREND:event_clickedAddFromMainPan
        // TODO add your handling code here:
        mainPan.setVisible(false);
        addPan.setVisible(true);
        fullTimeInputsPan.setVisible(false);
        partTimeInputsPan.setVisible(false);
        empExistNotice.setVisible(false);
        saveSuccessNotice.setVisible(false);
        clearSelectionsInAdd();
    }//GEN-LAST:event_clickedAddFromMainPan

    private void clickedHomeButFromAddPan(java.awt.event.ActionEvent evt)//GEN-FIRST:event_clickedHomeButFromAddPan
    {//GEN-HEADEREND:event_clickedHomeButFromAddPan
        // TODO add your handling code here:
        addPan.setVisible(false);
        mainPan.setVisible(true);
        clearSelectionsInAdd();

    }//GEN-LAST:event_clickedHomeButFromAddPan

    private void clearSelectionsInAdd()
    {
        empNumInput.setText(null);
        fNameInput.setText(null);
        lNameInput.setText(null);
        genderSelectionRadButGroup.clearSelection();
        workLocationDropdown.setSelectedIndex(0);
        empTypeSelectionRadButGroup.clearSelection();
        annualSalaryInput.setText(null);
        hourlyWageInput.setText(null);
        hoursPerWeekInput.setText(null);
        weeksPerYearInput.setText(null);
        deductionsRateInput.setText(null);
        fullTimeInputsPan.setVisible(false);
        partTimeInputsPan.setVisible(false);
    }
    
    private void fullTimeRadButClicked(java.awt.event.ActionEvent evt)//GEN-FIRST:event_fullTimeRadButClicked
    {//GEN-HEADEREND:event_fullTimeRadButClicked
        // TODO add your handling code here:
        fullTimeInputsPan.setVisible(false);
        partTimeInputsPan.setVisible(true);
    }//GEN-LAST:event_fullTimeRadButClicked

    private void partTimeRadButClicked(java.awt.event.ActionEvent evt)//GEN-FIRST:event_partTimeRadButClicked
    {//GEN-HEADEREND:event_partTimeRadButClicked
        // TODO add your handling code here:
        partTimeInputsPan.setVisible(false);
        fullTimeInputsPan.setVisible(true);
    }//GEN-LAST:event_partTimeRadButClicked

    private void clickedCanelButFromAddPan(java.awt.event.ActionEvent evt)//GEN-FIRST:event_clickedCanelButFromAddPan
    {//GEN-HEADEREND:event_clickedCanelButFromAddPan
        // TODO add your handling code here:
        addPan.setVisible(false);
        mainPan.setVisible(true);
        clearSelectionsInAdd();
    }//GEN-LAST:event_clickedCanelButFromAddPan

    private void homeButFromRemovePanclicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButFromRemovePanclicked
        // TODO add your handling code here:
        removePan.setVisible(false);
        mainPan.setVisible(true);
    }//GEN-LAST:event_homeButFromRemovePanclicked

    private void searchButToRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButToRemoveActionPerformed
        // TODO add your handling code here:
        int tempEmpNum = Integer.parseInt(empNumRemoveSearchInput.getText());
        theTable.search(tempEmpNum);
        
        if (theTable.search(tempEmpNum) < 0)
        {
            notFoundLabel.setVisible(true);
            removeResultPan.setVisible(false);
        } else
        {
            removeResultPan.setVisible(true);
            notFoundLabel.setVisible(false);
            removeSuccessNotice.setVisible(false);
            setSize(1280, 960);
            removePan.setSize(1280, 960);
            
            DefaultTableModel model = (DefaultTableModel) outPutTable1.getModel();
            int a = theTable.calcBuckets(tempEmpNum);
            int b = theTable.search(tempEmpNum);
            
                if (theTable.getBuckets()[a].get(b) instanceof FullTimeEmployee) {
                    FullTimeEmployee realFullTimeEmp = (FullTimeEmployee) theTable.getBuckets()[a].get(b);
                    String sexOutput=null;
                    String workLocOutput=null;
                    if (realFullTimeEmp.getSex()==0)
                        sexOutput = "Male";
                    else if (realFullTimeEmp.getSex()==1)
                        sexOutput = "Female";
                    else if (realFullTimeEmp.getSex()==2)
                        sexOutput = "Other";
                    if (realFullTimeEmp.getWorkLocation()==0)
                        workLocOutput= "Mississauga";
                    else if (realFullTimeEmp.getWorkLocation()==1)
                        workLocOutput = "Ottawa";
                    else if (realFullTimeEmp.getWorkLocation()==2)
                        workLocOutput = "Chicago";
                    model.addRow (new Object[]{realFullTimeEmp.getEmpNum(),realFullTimeEmp.getFirstName(),realFullTimeEmp.getLastName(),
                    sexOutput,workLocOutput,realFullTimeEmp.getDeductionsRate()*100+"%","*","-",realFullTimeEmp.getAnnualSalary(),"-","-","-",realFullTimeEmp.calcAnnualIncome()});
                }
                else if (theTable.getBuckets()[a].get(b) instanceof PartTimeEmployee) {
                    PartTimeEmployee realPartTimeEmp = (PartTimeEmployee) theTable.getBuckets()[a].get(b);
                String sexOutput=null;
                    String workLocOutput=null;
                    if (realPartTimeEmp.getSex()==0)
                        sexOutput = "Male";
                    else if (realPartTimeEmp.getSex()==1)
                        sexOutput = "Female";
                    else if (realPartTimeEmp.getSex()==2)
                        sexOutput = "Other";
                    if (realPartTimeEmp.getWorkLocation()==0)
                        workLocOutput= "Mississauga";
                    else if (realPartTimeEmp.getWorkLocation()==1)
                        workLocOutput = "Ottawa";
                    else if (realPartTimeEmp.getWorkLocation()==2)
                        workLocOutput = "Chicago"; 
                }
        }
    }//GEN-LAST:event_searchButToRemoveActionPerformed

    private void clickedExitButFromMainPan(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickedExitButFromMainPan
        // TODO add your handling code here:
        System.exit(0);
        /*    the file writter that will save to a text file
         try
         {
            BufferedWriter writer;
            writer = new BufferedWriter(new FileWriter(".\\SavedEmployeeData.txt"));
            writer.write(theTable.displayContents());
            writer.close();
        } catch (IOException ex)
        {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_clickedExitButFromMainPan

    private void exitBut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBut1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBut1ActionPerformed

    private void exitBut2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBut2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBut2ActionPerformed

    private void clickedRemoveFromMainPan(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickedRemoveFromMainPan
        // TODO add your handling code here:
        removePan.setVisible(true);
        mainPan.setVisible(false);
        notFoundLabel.setVisible(false);
        removeResultPan.setVisible(false);
        searchPan.setVisible(false);
        empNumRemoveSearchInput.setText(null);
    }//GEN-LAST:event_clickedRemoveFromMainPan

    private void clickedSaveButFromAddPan(java.awt.event.ActionEvent evt)//GEN-FIRST:event_clickedSaveButFromAddPan
    {//GEN-HEADEREND:event_clickedSaveButFromAddPan
        // TODO add your handling code here:
        int tempEmpNum = Integer.parseInt(empNumInput.getText());
        String tempFName = fNameInput.getText();
        String tempLName = lNameInput.getText();
        int tempSex = 0;
        if (maleRadBut.isSelected() == true)
        {
            tempSex = 0;
        } else if (femaleRadBut.isSelected() == true)
        {
            tempSex = 1;
        } else if (otherRadBut.isSelected() == true)
        {
            tempSex = 2;
        }
        int tempWorkLocation = 0;
        if (workLocationDropdown.getSelectedIndex() == 1)
        {
            tempWorkLocation = 0;
        } else if (workLocationDropdown.getSelectedIndex() == 2)
        {
            tempWorkLocation = 1;
        } else if (workLocationDropdown.getSelectedIndex() == 3)
        {
            tempWorkLocation = 2;
        }
        double tempDeductionsRate = Double.parseDouble(deductionsRateInput.getText())/100;

        double tempAnnualSalary = 0;
        double tempHourlyWage = 0;
        int tempHoursPerWeek = 0;
        int tempWeeksPerYear = 0;

        if (theTable.search(tempEmpNum) == -1)
        {
            if (fullTimeRadBut.isSelected() == true)
            {
                tempAnnualSalary = Double.parseDouble(annualSalaryInput.getText());
            } else if (partTimeRadBut.isSelected() == true)
            {
                tempHourlyWage = Double.parseDouble(hourlyWageInput.getText());
                tempHoursPerWeek = Integer.parseInt(hoursPerWeekInput.getText());
                tempWeeksPerYear = Integer.parseInt(weeksPerYearInput.getText());
            }
            FullTimeEmployee tempFullEmp = new FullTimeEmployee(tempEmpNum, tempFName, tempLName, tempSex, tempWorkLocation, tempDeductionsRate, tempAnnualSalary);
            PartTimeEmployee tempPartEmp = new PartTimeEmployee(tempEmpNum, tempFName, tempLName, tempSex, tempWorkLocation, tempDeductionsRate, tempHourlyWage, tempHoursPerWeek, tempWeeksPerYear);

            if (fullTimeRadBut.isSelected() == true)
            {
                theTable.add(tempFullEmp);
            } else if (partTimeRadBut.isSelected() == true)
            {
                theTable.add(tempPartEmp);
            }
            empExistNotice.setVisible(false);
            saveSuccessNotice.setVisible(true);
            clearSelectionsInAdd();
        } else
        {
            saveSuccessNotice.setVisible(false);
            empExistNotice.setVisible(true);
            clearSelectionsInAdd();
        }

        theTable.displayContents();


    }//GEN-LAST:event_clickedSaveButFromAddPan

    private void workLocationDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workLocationDropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_workLocationDropdownActionPerformed

    private void clickedHomeButFromSearchPan(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickedHomeButFromSearchPan
        // TODO add your handling code here:
        searchPan.setVisible(false);
        mainPan.setVisible(true);
    }//GEN-LAST:event_clickedHomeButFromSearchPan

    private void clickedSearchButFromSearchPan(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickedSearchButFromSearchPan
        // TODO add your handling code here:
        int tempEmpNumInput = Integer.parseInt(empNumSearchInput.getText());
        if (theTable.search(tempEmpNumInput) < 0)
        {
            notFoundLabelSearchPan.setVisible(true);
        } else
        {
            searchResultPan.setVisible(true);
            notFoundLabelSearchPan.setVisible(false);
            empInfoDisplayLabel1.setText(theTable.displayOneEmp(tempEmpNumInput));
        }
    }//GEN-LAST:event_clickedSearchButFromSearchPan

    private void exitBut3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBut3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBut3ActionPerformed

    private void empInfoDisplayLabel1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_empInfoDisplayLabel1InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_empInfoDisplayLabel1InputMethodTextChanged

    private void clickedSearchButFromMainPan(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickedSearchButFromMainPan
        // TODO add your handling code here:
        mainPan.setVisible(false);
        searchPan.setVisible(true);
        searchResultPan.setVisible(false);
        notFoundLabelSearchPan.setVisible(false);

    }//GEN-LAST:event_clickedSearchButFromMainPan

    private void clickedDisplayButFromMainPan(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickedDisplayButFromMainPan
        // TODO add your handling code here:
        mainPan.setVisible(false);
        setSize(1280, 960);
        displayPan.setSize(1280, 960);
        displayPan.setVisible(true);
        
   DefaultTableModel model = (DefaultTableModel) outPutTable.getModel();
   
        for (int a = 0; a < theTable.getBuckets().length; a++)
        {
            for (int b = 0; b < theTable.getBuckets()[a].size(); b++)  
            {                
                if (theTable.getBuckets()[a].get(b) instanceof FullTimeEmployee) {
                    FullTimeEmployee realFullTimeEmp = (FullTimeEmployee) theTable.getBuckets()[a].get(b);
                    String sexOutput=null;
                    String workLocOutput=null;
                    if (realFullTimeEmp.getSex()==0)
                        sexOutput = "Male";
                    else if (realFullTimeEmp.getSex()==1)
                        sexOutput = "Female";
                    else if (realFullTimeEmp.getSex()==2)
                        sexOutput = "Other";
                    if (realFullTimeEmp.getWorkLocation()==0)
                        workLocOutput= "Mississauga";
                    else if (realFullTimeEmp.getWorkLocation()==1)
                        workLocOutput = "Ottawa";
                    else if (realFullTimeEmp.getWorkLocation()==2)
                        workLocOutput = "Chicago";
                    model.addRow (new Object[]{realFullTimeEmp.getEmpNum(),realFullTimeEmp.getFirstName(),realFullTimeEmp.getLastName(),
                    sexOutput,workLocOutput,realFullTimeEmp.getDeductionsRate()*100+"%","*","-",realFullTimeEmp.getAnnualSalary(),"-","-","-",realFullTimeEmp.calcAnnualIncome()});
                }
                else if (theTable.getBuckets()[a].get(b) instanceof PartTimeEmployee) {
                    PartTimeEmployee realPartTimeEmp = (PartTimeEmployee) theTable.getBuckets()[a].get(b);
                String sexOutput=null;
                    String workLocOutput=null;
                    if (realPartTimeEmp.getSex()==0)
                        sexOutput = "Male";
                    else if (realPartTimeEmp.getSex()==1)
                        sexOutput = "Female";
                    else if (realPartTimeEmp.getSex()==2)
                        sexOutput = "Other";
                    if (realPartTimeEmp.getWorkLocation()==0)
                        workLocOutput= "Mississauga";
                    else if (realPartTimeEmp.getWorkLocation()==1)
                        workLocOutput = "Ottawa";
                    else if (realPartTimeEmp.getWorkLocation()==2)
                        workLocOutput = "Chicago"; 
                    model.addRow (new Object[]{realPartTimeEmp.getEmpNum(),realPartTimeEmp.getFirstName(),realPartTimeEmp.getLastName(),
                    sexOutput,workLocOutput,realPartTimeEmp.getDeductionsRate()*100+"%","-","*","-",realPartTimeEmp.getHourlyWage(),realPartTimeEmp.getHoursPerWeek(),
                    realPartTimeEmp.getWeeksPerYear(),realPartTimeEmp.calcAnnualIncome()});
                }
            }
        }



    }//GEN-LAST:event_clickedDisplayButFromMainPan

    private void exitBut4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_exitBut4ActionPerformed
    {//GEN-HEADEREND:event_exitBut4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBut4ActionPerformed

    private void clickedHomeButFromDisplayPan(java.awt.event.ActionEvent evt)//GEN-FIRST:event_clickedHomeButFromDisplayPan
    {//GEN-HEADEREND:event_clickedHomeButFromDisplayPan
        // TODO add your handling code here:
        displayPan.setVisible(false);
        setSize(600,470);
        mainPan.setVisible(true);
    }//GEN-LAST:event_clickedHomeButFromDisplayPan

    private void fNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNameInputActionPerformed

    private void clickedYesButFromRemovePan(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickedYesButFromRemovePan
        // TODO add your handling code here:
        int tempEmpNumInput = Integer.parseInt(empNumRemoveSearchInput.getText());
        theTable.remove(tempEmpNumInput);
        notFoundLabel.setVisible(false);
        removeResultPan.setVisible(false);
        removeSuccessNotice.setVisible(true);
    }//GEN-LAST:event_clickedYesButFromRemovePan

    private void clickedNoButFromRemovePan(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickedNoButFromRemovePan
        // TODO add your handling code here:
        notFoundLabel.setVisible(false);
        removeResultPan.setVisible(false);
    }//GEN-LAST:event_clickedNoButFromRemovePan

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                

}
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(MainMenu.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(MainMenu.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(MainMenu.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MainMenu.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JButton addBut;
    private javax.swing.JPanel addPan;
    private javax.swing.JLabel addTitle;
    private javax.swing.JFormattedTextField annualSalaryInput;
    private javax.swing.JLabel annualSalaryLabel;
    private javax.swing.JButton cancelButFromAddPan;
    private javax.swing.JFormattedTextField deductionsRateInput;
    private javax.swing.JLabel deductionsRateLabel;
    private javax.swing.JLabel diaplayTitle;
    private javax.swing.JButton displayBut;
    private javax.swing.JPanel displayPan;
    private javax.swing.JLabel empExistNotice;
    private javax.swing.JLabel empInfoDisplayLabel1;
    private javax.swing.JFormattedTextField empNumInput;
    private javax.swing.JLabel empNumLabel;
    private javax.swing.JTextField empNumRemoveSearchInput;
    private javax.swing.JTextField empNumSearchInput;
    private javax.swing.ButtonGroup empTypeSelectionRadButGroup;
    private javax.swing.JLabel employeeNumberLabel;
    private javax.swing.JLabel employeeNumberLabel1;
    private javax.swing.JLabel employeeTypeLabel;
    private javax.swing.JLabel errorEmpNum;
    private javax.swing.JButton exitBut;
    private javax.swing.JButton exitBut1;
    private javax.swing.JButton exitBut2;
    private javax.swing.JButton exitBut3;
    private javax.swing.JButton exitBut4;
    private javax.swing.JTextField fNameInput;
    private javax.swing.JLabel fNameLabel;
    private javax.swing.JRadioButton femaleRadBut;
    private javax.swing.JPanel fullTimeInputsPan;
    private javax.swing.JRadioButton fullTimeRadBut;
    private javax.swing.ButtonGroup genderSelectionRadButGroup;
    private javax.swing.JButton homeButFromAddPan;
    private javax.swing.JButton homeButFromRemovePan;
    private javax.swing.JButton homeButFromRemovePan1;
    private javax.swing.JButton homeButFromRemovePan2;
    private javax.swing.JFormattedTextField hourlyWageInput;
    private javax.swing.JLabel hourlyWageLabel;
    private javax.swing.JFormattedTextField hoursPerWeekInput;
    private javax.swing.JLabel hoursPerWeekLabel;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lNameInput;
    private javax.swing.JLabel lNameLabel;
    private javax.swing.JButton loadBut;
    private javax.swing.JPanel mainPan;
    private javax.swing.JRadioButton maleRadBut;
    private javax.swing.JButton modifyBut;
    private javax.swing.JLabel notFoundLabel;
    private javax.swing.JLabel notFoundLabelSearchPan;
    private javax.swing.JLabel note2Label;
    private javax.swing.JLabel note2Label1;
    private javax.swing.JRadioButton otherRadBut;
    private javax.swing.JTable outPutTable;
    private javax.swing.JTable outPutTable1;
    private javax.swing.JPanel partTimeInputsPan;
    private javax.swing.JRadioButton partTimeRadBut;
    private javax.swing.JLabel percentSymbolLabel;
    private javax.swing.JButton removeBut;
    private javax.swing.JLabel removeConfirmLabel;
    private javax.swing.JButton removeNoBut;
    private javax.swing.JLabel removeNoteLabel;
    private javax.swing.JPanel removePan;
    private javax.swing.JPanel removeResultPan;
    private javax.swing.JLabel removeSuccessNotice;
    private javax.swing.JLabel removeTitle;
    private javax.swing.JButton removeYesBut;
    private javax.swing.JButton saveButFromAddPan;
    private javax.swing.JLabel saveSuccessNotice;
    private javax.swing.JButton searchBut;
    private javax.swing.JButton searchButToRemove;
    private javax.swing.JButton searchButToRemove1;
    private javax.swing.JLabel searchNoteLabel1;
    private javax.swing.JPanel searchPan;
    private javax.swing.JPanel searchResultPan;
    private javax.swing.JLabel searchTitle1;
    private javax.swing.JLabel sexLabel;
    private javax.swing.JFormattedTextField weeksPerYearInput;
    private javax.swing.JLabel weeksPerYearLabel;
    private javax.swing.JComboBox<String> workLocationDropdown;
    private javax.swing.JLabel workLocationLabel;
    // End of variables declaration//GEN-END:variables
}
